import './globals.css';
import type { Metadata } from 'next';

import Layout from '@/components/layout/Layout';
import StyledComponentsRegistry from '@/lib/registry';

export const metadata: Metadata = {
  title: 'Daniel Nguyen | Portfolio',
  description: 'Generated by create next app',
};

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang='en'>
      <body>
        <StyledComponentsRegistry>
          <Layout>{children}</Layout>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
};

export default RootLayout;
